apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-kubernetes-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shubham-casio21/gitops-kubernetes-platform.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
